name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
         username: abderrahimdev
         password: dckr_pat_8jKbbZdVUvcvZTkl_Mt3rfC9yGI

    - name: Build Docker image
      run: |
        docker build -t maroc_erp/axelor-erp . 
    - name: Push Docker image to Docker Hub
      run: |
        docker push maroc_erp/axelor-erp
